# Generated by Django 2.2.4 on 2019-08-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_at',
            new_name='last_update',
        ),
    ]
